name: Release Canary to NPM

on:
  push:
    branches-ignore:
      - main

jobs:
  release-canary:
    name: Release Canary to NPM
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # token: ${{ secrets.NPM_TOKEN }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn ci

      - name: Create Release Pull Request or publish to NPM
        uses: changesets/action@v1
        with:
          version: yarn version:snapshot
          publish: yarn release --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
